/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlApi_listInstallations"];
        put?: never;
        post: operations["ControlApi_createInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/installations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ControlApi_updateInstallation"];
        trace?: never;
    };
    "/api/v1/installations/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ControlApi_rotateInstallationToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlApi_listProviders"];
        put?: never;
        post: operations["ControlApi_createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ControlApi_updateProvider"];
        trace?: never;
    };
    "/api/v1/resolvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlApi_listResolverAccounts"];
        put?: never;
        post: operations["ControlApi_createResolverAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolvers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ControlApi_updateResolverAccount"];
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ControlApi_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateInstallationRequest: {
            name: string;
            /** @enum {string} */
            clientMode: "stremio" | "nuvio" | "universal";
            /** @enum {string} */
            resolutionMode: "client" | "server" | "hybrid";
            resolverId?: string;
            enabled: boolean;
        };
        CreateProviderRequest: {
            name: string;
            kind: components["schemas"]["ProviderKind"];
            preset?: components["schemas"]["RemoteAddonPreset"];
            endpoint: string;
            apiKey?: string;
            enabled: boolean;
        };
        CreateResolverAccountRequest: {
            name: string;
            kind: components["schemas"]["ResolverKind"];
            apiKey: string;
            enabled: boolean;
            proxyUrl?: string;
        };
        Installation: {
            id: string;
            name: string;
            /** @enum {string} */
            clientMode: "stremio" | "nuvio" | "universal";
            /** @enum {string} */
            resolutionMode: "client" | "server" | "hybrid";
            resolverId?: string;
            enabled: boolean;
        };
        InstallationListResponse: {
            items: components["schemas"]["Installation"][];
        };
        Provider: {
            id: string;
            name: string;
            kind: components["schemas"]["ProviderKind"];
            endpoint: string;
            enabled: boolean;
        };
        /** @enum {string} */
        ProviderKind: "remote-addon" | "torznab" | "newznab" | "prowlarr" | "jackett" | "nzbhydra2" | "eztv" | "knaben" | "the-pirate-bay" | "therarbg" | "torrent-galaxy" | "torbox-search";
        ProviderListResponse: {
            items: components["schemas"]["Provider"][];
        };
        /** @enum {string} */
        RemoteAddonPreset: "torrentio" | "comet" | "mediafusion";
        ResolverAccount: {
            id: string;
            name: string;
            kind: components["schemas"]["ResolverKind"];
            enabled: boolean;
            proxyEnabled: boolean;
        };
        ResolverAccountListResponse: {
            items: components["schemas"]["ResolverAccount"][];
        };
        /** @enum {string} */
        ResolverKind: "realdebrid" | "debridlink" | "premiumize" | "alldebrid" | "torbox" | "easydebrid" | "debrider" | "pikpak" | "offcloud" | "torrin";
        StatusResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** @enum {string} */
            database: "up" | "down" | "disabled";
            /** @enum {string} */
            secrets: "ready" | "disabled";
        };
        UpdateInstallationRequest: {
            enabled: boolean;
        };
        UpdateProviderRequest: {
            enabled: boolean;
        };
        UpdateResolverAccountRequest: {
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ControlApi_listInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationListResponse"];
                };
            };
        };
    };
    ControlApi_createInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstallationRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Installation"];
                };
            };
        };
    };
    ControlApi_updateInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInstallationRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Installation"];
                };
            };
        };
    };
    ControlApi_rotateInstallationToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Installation"];
                };
            };
        };
    };
    ControlApi_listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
        };
    };
    ControlApi_createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    ControlApi_updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
        };
    };
    ControlApi_listResolverAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolverAccountListResponse"];
                };
            };
        };
    };
    ControlApi_createResolverAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResolverAccountRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolverAccount"];
                };
            };
        };
    };
    ControlApi_updateResolverAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResolverAccountRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolverAccount"];
                };
            };
        };
    };
    ControlApi_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
