package resolver

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"streamweave/internal/domain"
	"streamweave/internal/engine"
	"streamweave/internal/safehttp"
)

func ValidateProxyURL(raw string) error {
	u, err := url.Parse(raw)
	if err != nil || u == nil || u.Hostname() == "" || u.Fragment != "" || u.Path != "" || u.RawQuery != "" || (u.Scheme != "http" && u.Scheme != "https" && u.Scheme != "socks5") {
		return errors.New("proxyUrl must be an HTTP, HTTPS or SOCKS5 proxy URL with a host")
	}
	return nil
}

func proxyClient(raw string) (*http.Client, error) {
	if err := ValidateProxyURL(raw); err != nil {
		return nil, err
	}
	u, _ := url.Parse(raw)
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.Proxy = http.ProxyURL(u)
	transport.ResponseHeaderTimeout = 20 * time.Second
	return &http.Client{Transport: transport, Timeout: 18 * time.Second, CheckRedirect: func(req *http.Request, via []*http.Request) error {
		if len(via) >= 5 || (len(via) > 0 && via[len(via)-1].URL.Scheme == "https" && req.URL.Scheme != "https") {
			return errors.New("unsafe redirect")
		}
		return safehttp.ValidatePublicURL(req.URL.String())
	}}, nil
}

type proxyResolver struct {
	engine.Resolver
	accountID string
	box       interface{ SealURL([]byte) (string, error) }
}

type streamToken struct {
	Account string            `json:"a"`
	URL     string            `json:"u"`
	Headers map[string]string `json:"h,omitempty"`
	Expires int64             `json:"e"`
}

func (r proxyResolver) Resolve(ctx context.Context, candidate domain.Candidate) (domain.Candidate, error) {
	result, err := r.Resolver.Resolve(ctx, candidate)
	if err != nil || result.HTTP == nil {
		return result, err
	}
	if err = safehttp.ValidatePublicURL(result.HTTP.URL); err != nil {
		return candidate, err
	}
	data, err := json.Marshal(streamToken{Account: r.accountID, URL: result.HTTP.URL, Headers: result.HTTP.Headers, Expires: time.Now().Add(4 * time.Hour).Unix()})
	if err != nil {
		return candidate, err
	}
	token, err := r.box.SealURL(data)
	if err != nil {
		return candidate, err
	}
	result.HTTP = &domain.HTTPStream{URL: "/api/v1/proxy/stream/" + token}
	return result, nil
}

// ServeStream relays only links generated by an enabled account with an active proxy.
func (s *Source) ServeStream(w http.ResponseWriter, r *http.Request, token string) {
	if s.secrets == nil || len(token) > 8192 {
		http.NotFound(w, r)
		return
	}
	data, err := s.secrets.OpenURL(token)
	var payload streamToken
	if err != nil || json.Unmarshal(data, &payload) != nil || payload.Expires < time.Now().Unix() || payload.Expires > time.Now().Add(4*time.Hour).Unix()+60 || safehttp.ValidatePublicURL(payload.URL) != nil {
		http.NotFound(w, r)
		return
	}
	id, err := uuid.Parse(payload.Account)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	account, err := s.queries.GetResolverAccount(r.Context(), pgtype.UUID{Bytes: id, Valid: true})
	if err != nil || !account.Enabled || len(account.ProxyCiphertext) == 0 {
		http.NotFound(w, r)
		return
	}
	proxy, err := s.secrets.Open(account.ProxyCiphertext, account.ProxyNonce)
	if err != nil {
		http.Error(w, "stream unavailable", http.StatusBadGateway)
		return
	}
	client, err := proxyClient(string(proxy))
	if err != nil {
		http.Error(w, "stream unavailable", http.StatusBadGateway)
		return
	}
	client.Timeout = 0
	upstream, err := http.NewRequestWithContext(r.Context(), r.Method, payload.URL, nil)
	if err != nil {
		http.Error(w, "stream unavailable", http.StatusBadGateway)
		return
	}
	for name, value := range payload.Headers {
		if strings.EqualFold(name, "Host") || strings.EqualFold(name, "Connection") || strings.EqualFold(name, "Range") {
			continue
		}
		upstream.Header.Set(name, value)
	}
	if value := r.Header.Get("Range"); value != "" {
		upstream.Header.Set("Range", value)
	}
	response, err := client.Do(upstream)
	if err != nil {
		http.Error(w, "stream unavailable", http.StatusBadGateway)
		return
	}
	defer response.Body.Close()
	_ = http.NewResponseController(w).SetWriteDeadline(time.Time{})
	for _, name := range []string{"Content-Type", "Content-Length", "Content-Range", "Accept-Ranges", "ETag", "Last-Modified"} {
		if value := response.Header.Get(name); value != "" {
			w.Header().Set(name, value)
		}
	}
	w.WriteHeader(response.StatusCode)
	_, _ = io.Copy(w, response.Body)
}
